web: gunicorn apptech:app

worker: gunicorn GetCustomerDetails.py
worker: gunicorn GetCustomerDetailsAll.py
worker: gunicorn GetBookedAppointmentSlot.py
worker: gunicorn QueryBusinessPrimaryData.py
worker: gunicorn Update.py
worker: gunicorn UpdateCustomerStatus.py
worker: gunicorn UpdateCustomerFeedback.py
worker: gunicorn QueryBusinessDetailsData.py
worker: gunicorn GetAppointmentSchedule.py
worker: gunicorn GetLastCheckedoutTokenNum.py
worker: gunicorn GetLiveFeed.py
worker: gunicorn TokenNumberGeneration.py
worker: gunicorn InsertBusinessPrimaryData.py
worker: gunicorn InsertBusinessDetailsData.py
worker: gunicorn QueryBusinessPrimaryAll.py
worker: gunicorn AverageWaitTime.py
worker: gunicorn GetCustomerBusinessDetails.py
worker: gunicorn AppointmentChatbots.py
worker: gunicorn weather.py
worker: gunicorn UpdateBusinessPrimaryData.py
worker: gunicorn SendEmail.py
worker: gunicorn InsertCustomerLoginData.py
worker: gunicorn QueryCustomerLoginData.py
worker: gunicorn PushNotificationAll.py
worker: gunicorn GetBusinessReportAll.py
worker: gunicorn GetBusinessReportIndividual.py
worker: gunicorn SendEmailAll.py
worker: gunicorn GetBusinessReportIndividualDate.py
worker: gunicorn SendSms.py
worker: gunicorn schedulesms.py
